package aeon.modelo.dto;
// Generated 10-10-2018 06:07:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roll generated by hbm2java
 */
public class Roll  implements java.io.Serializable {


     private int rollId;
     private String rollName;


    public Roll() {
    }

	
    public Roll(int rollId, String rollName) {
        this.rollId = rollId;
        this.rollName = rollName;
    }

   
    public int getRollId() {
        return this.rollId;
    }
    
    public void setRollId(int rollId) {
        this.rollId = rollId;
    }
    public String getRollName() {
        return this.rollName;
    }
    
    public void setRollName(String rollName) {
        this.rollName = rollName;
    }

    @Override
    public String toString() {
        return "Roll{" + "rollId=" + rollId + ", rollName=" + rollName + '}';
    }


}


