package aeon.modelo.dto;
// Generated 10-10-2018 06:07:14 PM by Hibernate Tools 4.3.1



/**
 * RollSubmenu generated by hbm2java
 */
public class RollSubmenu  implements java.io.Serializable {


     private int rollSubmenuId;
     private int roll;
     private int subMenu;
     private int estado;
     private String subMenuname;
     private String rollName;

    public RollSubmenu() {
    }

	
    public RollSubmenu(int rollSubmenuId, int estado) {
        this.rollSubmenuId = rollSubmenuId;
        this.estado = estado;
    }

    public int getRollSubmenuId() {
        return this.rollSubmenuId;
    }
    
    public void setRollSubmenuId(int rollSubmenuId) {
        this.rollSubmenuId = rollSubmenuId;
    }
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }
    public int getSubMenu() {
        return this.subMenu;
    }
    
    public void setSubMenu(int subMenu) {
        this.subMenu = subMenu;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    public String getSubMenuname() {
        return subMenuname;
    }

    public void setSubMenuname(String subMenuname) {
        this.subMenuname = subMenuname;
    }

    public String getRollName() {
        return rollName;
    }

    public void setRollName(String rollName) {
        this.rollName = rollName;
    }




}


