package aeon.modelo.dto;
// Generated 10-10-2018 06:07:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubMenu generated by hbm2java
 */
public class SubMenu  implements java.io.Serializable {


     private int summenuId;
     private int menu;
     private String submenuName;
     private String url;

    public SubMenu() {
    }

	
    public SubMenu(int summenuId, String submenuName, String url) {
        this.summenuId = summenuId;
        this.submenuName = submenuName;
        this.url = url;
    }

    public int getSummenuId() {
        return this.summenuId;
    }
    
    public void setSummenuId(int summenuId) {
        this.summenuId = summenuId;
    }
    public int getMenu() {
        return this.menu;
    }
    
    public void setMenu(int menu) {
        this.menu = menu;
    }
    public String getSubmenuName() {
        return this.submenuName;
    }
    
    public void setSubmenuName(String submenuName) {
        this.submenuName = submenuName;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public String toString() {
        return "SubMenu{" + "summenuId=" + summenuId + ", menu=" + menu + ", submenuName=" + submenuName + ", url=" + url + '}';
    }



}


