package aeon.modelo.dto;
// Generated 10-10-2018 06:07:14 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String usuario;
     private int roll;
     private String nombre;
     private String contrasena;
     private Integer estadousuario;


    public Usuario() {
    }

	
    public Usuario(String usuario) {
        this.usuario = usuario;
    }

   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Integer getEstadousuario() {
        return this.estadousuario;
    }
    
    public void setEstadousuario(Integer estadousuario) {
        this.estadousuario = estadousuario;
    }

}


