package aeon.modelo.dto;
// Generated 10-10-2018 06:07:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private int idventa;
     private Usuario usuario;
     private Date fecha;
     private Float totalpagar;
     private Integer estadoventa;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(int idventa, Date fecha) {
        this.idventa = idventa;
        this.fecha = fecha;
    }
    public Venta(int idventa, Usuario usuario, Date fecha, Float totalpagar, Integer estadoventa, Set detalleVentas) {
       this.idventa = idventa;
       this.usuario = usuario;
       this.fecha = fecha;
       this.totalpagar = totalpagar;
       this.estadoventa = estadoventa;
       this.detalleVentas = detalleVentas;
    }
   
    public int getIdventa() {
        return this.idventa;
    }
    
    public void setIdventa(int idventa) {
        this.idventa = idventa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Float getTotalpagar() {
        return this.totalpagar;
    }
    
    public void setTotalpagar(Float totalpagar) {
        this.totalpagar = totalpagar;
    }
    public Integer getEstadoventa() {
        return this.estadoventa;
    }
    
    public void setEstadoventa(Integer estadoventa) {
        this.estadoventa = estadoventa;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


